# Generated by Django 3.2.7 on 2021-10-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AgregateDataPoint",
            new_name="AggregateDataPoint",
        ),
        migrations.RemoveField(
            model_name="spot",
            name="sunrise_utc",
        ),
        migrations.RemoveField(
            model_name="spot",
            name="sunset_utc",
        ),
        migrations.CreateModel(
            name="AverageDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.spot"
                    ),
                ),
            ],
        ),
    ]
