# Generated by Django 3.2.5 on 2021-09-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("major_city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=200, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("sunrise", models.DateTimeField(blank=True, null=True)),
                ("sunrise_utc", models.DateTimeField(blank=True, null=True)),
                ("sunset", models.DateTimeField(blank=True, null=True)),
                ("sunset_utc", models.DateTimeField(blank=True, null=True)),
                ("current_count", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetectionDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("count", models.IntegerField(default=0)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.spot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgregateDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.spot"
                    ),
                ),
            ],
        ),
    ]
