# Generated by Django 3.2.8 on 2021-11-12 14:50

import counter.enums
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_spot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedatapoint',
            name='month_id',
            field=enumfields.fields.EnumIntegerField(enum=counter.enums.MonthIdentifierEnum, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='_sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='_sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aggregatedatapoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='averagedatapoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectiondatapoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hourlyaveragedatapoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='sunrise',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='sunset',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
