# Generated by Django 3.2.8 on 2021-11-12 15:19

import counter.enums
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20211112_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedatapoint',
            name='day_id',
            field=enumfields.fields.EnumIntegerField(enum=counter.enums.DayIdentifierEnum, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='now',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
