# Generated by Django 3.2.7 on 2021-10-07 17:14

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import counter.models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0002_auto_20211002_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="averagedatapoint",
            name="hour_id",
            field=enumfields.fields.EnumIntegerField(
                enum=counter.models.HourIdentifierEnum, null=True
            ),
        ),
        migrations.CreateModel(
            name="HourlyAverageDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hour_id",
                    enumfields.fields.EnumIntegerField(
                        enum=counter.models.HourIdentifierEnum
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="counter.spot"
                    ),
                ),
            ],
        ),
    ]
