# Generated by Django 3.2.7 on 2021-10-12 17:36

import enumfields.fields
from django.db import migrations

import counter.enums


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0004_spot_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="averagedatapoint",
            name="month_id",
            field=enumfields.fields.EnumIntegerField(
                enum=counter.enums.MonthIdentifierEnum, null=True
            ),
        ),
    ]
