# Generated by Django 3.2.8 on 2021-11-11 17:16

import counter.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_averagedatapoint_month_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedatapoint',
            name='day_id',
            field=enumfields.fields.EnumIntegerField(enum=counter.enums.DayIdentifierEnum, null=True),
        ),
    ]
