# Generated by Django 3.2.7 on 2022-01-10 23:53

import counter.enums
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20211112_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfQualityDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', enumfields.fields.EnumField(enum=counter.enums.SurfQualityRating, max_length=12, null=True)),
                ('hour_id', enumfields.fields.EnumIntegerField(enum=counter.enums.HourIdentifierEnum, null=True)),
                ('day_id', enumfields.fields.EnumIntegerField(enum=counter.enums.DayIdentifierEnum, null=True)),
                ('month_id', enumfields.fields.EnumIntegerField(enum=counter.enums.MonthIdentifierEnum, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.spot')),
            ],
        ),
    ]
