# Generated by Django 3.2.7 on 2021-12-21 16:06

import counter.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_auto_20211112_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='current_surf_quality',
            field=enumfields.fields.EnumField(blank=True, enum=counter.enums.SurfQualityRating, max_length=12),
        ),
    ]
