name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: spot_data_tests
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        python-version: ['3.8']
    steps:

    - name: "Checkout code"
      uses: actions/checkout@v2

    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Install test dependencies"
      run: |
        pip install -r requirements.txt
  
    - name: "Install PostgreSQL client"
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends postgresql-client


    - name: "Create test database"
      run: psql -U postgres -h 127.0.0.1 << 'CREATE DATABASE spot_data_tests;'
      env:
        PGPASSWORD: postgres

    - name: "Run tests"
      env:
        SECRET_KEY: xxx
        DATABASE_NAME: spot_data_tests
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 5432
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/spot_data_tests
      

      run: py.test -vvv --nomigrations
